### ISSUE TITLE
No way to stop the algorithm execution

### ISSUE THREAD

**Issue by domizianooo** [AbhishekPrakash5/Sorting-Visualization#3]
I like your project, but when I tried to used it, I noticed that once the sorting algorithm was started, the only way to stop it (in order to visualize a different algorithm without waiting for the current one to finish) is to reload the page.
If you want I can implement a simple stop button, on the right of the "New Array" button, with the same style but colored in red.

**Comment by shivkantkumar098** [comment]
refresh the page it will stop
